update fr translations
LetsRoleRPG/wiki pull request #29
Opened 2021-03-10 11:20 UTC by Elanndelh

[System-Builder/Composants] add links; try to uniformize composants; correct texts

2021-03-11 09:53 UTC, Elanndelh commented
+infos level/race/class ids in both english/french

2021-03-14 14:24 UTC, dyzae requested changes
La row représente bien une rangé et pas une section.

2021-03-14 14:26 UTC, dyzae requested changes
Pareil ici, les row sont des rangées pas des sections.

2021-03-14 14:29 UTC, dyzae commented
Voilà juste me faire les petits correctifs demandé sur la traduction de "row" et je merge le tout! :)

2021-03-14 15:04 UTC, Elanndelh commented
C'est fait normalement !

2021-03-15 22:28 UTC, dyzae approved these changes

2021-03-15 22:28 UTC, dyzae approved these changes

2021-03-15 22:28 UTC, merged