WIP : Adding page that list all community systems
LetsRoleRPG/wiki pull request #5
Opened 2020-09-13 17:48 UTC by Tsuna77

Work in progress, PR open for an alpha review

2020-09-13 18:56 UTC, dyzae approved these changes

2020-09-13 18:59 UTC, LetsRoleRPG commented
Il manque les infos entre --- sur `system-list.md`

2020-09-13 19:06 UTC, dyzae approved these changes

2020-09-14 10:34 UTC, Tenshi-JDR requested changes

2020-09-14 10:34 UTC, Tenshi-JDR commented on fr/system-list.md
> +# Liste des systèmes créé par la communauté let's role
créés*
Let's Role*

2020-09-14 10:34 UTC, Tenshi-JDR commented on fr/system-list.md
> +Les systèmes ci-dessous ont été créé par la communauté et sont maintenu par leurs auteurs respectif.
créés*
maintenus*
respectifs*

2020-09-14 10:40 UTC, Tenshi-JDR commented on fr/system-list.md
> +| Jeu                                         | Auteur        | Langue  | lien système                                                                           | lien forum
Rajouter une case "contact" et un moyen de contacter l'auteur, s'il le désire ? Remonter des bugs sur un système sera plus aisé ainsi.

2020-09-14 18:31 UTC, Tsuna77 commented on fr/system-list.md
> +| Jeu                                         | Auteur        | Langue  | lien système                                                                           | lien forum
je pensais que le lien du forum était fait pour sa justement ^^ avoir une zone d'échange avec le créateur du système

2020-09-14 19:01 UTC, dyzae approved these changes

2020-09-14 19:02 UTC, dyzae approved these changes
C'est bon pour vos modifs

2020-09-15 12:26 UTC, dyzae commented on fr/system-list.md
> +| Jeu                                         | Auteur        | Langue  | lien système                                                                           | lien forum
Je pense effectivement que la colonne "lien forum" est suffisent, c'est là que les bug, suggestions et co' sont faite :)

2020-09-15 12:27 UTC, merged